Feat/contactus
SheCodesAus/2024_exception_al_frontend pull request #40
Opened 2024-04-06 02:37 UTC by boneycd

2024-04-06 04:57 UTC, suanTech requested changes

2024-04-06 04:57 UTC, suanTech commented on src/components/ContactUsForm.jsx
> +            name="username"
Please change name and id to match the field

2024-04-06 04:57 UTC, suanTech commented on src/components/ContactUsForm.jsx
> +          {error && error.field === "password" ? (
remove this part

2024-04-06 04:57 UTC, suanTech commented on src/components/ContactUsForm.jsx
> +
add a body with TextInput size="md"

2024-04-06 17:26 UTC, boneycd commented on src/components/ContactUsForm.jsx
> +            name="username"
Thanks Suan. Its done

2024-04-06 17:26 UTC, boneycd commented on src/components/ContactUsForm.jsx
> +          {error && error.field === "password" ? (
Thanks Suan. Its done

2024-04-06 17:27 UTC, boneycd commented on src/components/ContactUsForm.jsx
> +
Thanks Suan , Not sure if i did it right.

2024-04-06 17:29 UTC, boneycd commented
![Formspree](https://github.com/SheCodesAus/2024_exception_al_frontend/assets/147505486/1f5a1bc5-0509-4acf-8e34-76bf927ca0cf)

2024-04-07 00:37 UTC, suanTech requested changes
Great work Boney!! Just need a little change on texts.

2024-04-07 00:37 UTC, suanTech commented on src/components/ContactUsForm.jsx
> +        <p>Error while submitting the sign up form</p>
Please change the successful message, something like "Thanks for contacting us, we'll get back to you shortly."
And also button should navigate to the home page, with Go back to home text.

2024-04-07 02:33 UTC, suanTech approved these changes
Nice! Merge it in!

2024-04-07 02:34 UTC, merged